import { Quote } from '../types';

/**
 * Repertorio selecto de 150 frases icónicas de la historia del cine
 * en riguroso español latino para el público hispano.
 * Operación 100% estática / cliente (0 costo de lecturas a la base de datos).
 */
export const ICONIC_CINEMA_QUOTES: Quote[] = [
  // 1 - 25
  { text: "Le haré una oferta que no podrá rechazar.", movie: "El Padrino", character: "Don Vito Corleone" },
  { text: "Mantén a tus amigos cerca, pero a tus enemigos aún más cerca.", movie: "El Padrino II", character: "Michael Corleone" },
  { text: "Que la Fuerza te acompañe.", movie: "Star Wars: Una Nueva Esperanza", character: "Obi-Wan Kenobi" },
  { text: "No. Yo soy tu padre.", movie: "Star Wars: El Imperio Contraataca", character: "Darth Vader" },
  { text: "Hazlo o no lo hagas, pero no lo intentes.", movie: "Star Wars: El Imperio Contraataca", character: "Yoda" },
  { text: "El miedo es el camino hacia el Lado Oscuro. El miedo lleva a la ira, la ira al odio y el odio al sufrimiento.", movie: "Star Wars: La Amenaza Fantasma", character: "Yoda" },
  { text: "Hasta la vista, baby.", movie: "Terminator 2: El Juicio Final", character: "T-800" },
  { text: "Volveré.", movie: "Terminator", character: "T-800" },
  { text: "El futuro no está escrito. No hay más destino que el que nosotros mismos forjamos.", movie: "Terminator 2: El Juicio Final", character: "John Connor" },
  { text: "La vida es como una caja de bombones: nunca sabes lo que te va a tocar.", movie: "Forrest Gump", character: "Forrest Gump" },
  { text: "¡Corre, Forrest, corre!", movie: "Forrest Gump", character: "Jenny Curran" },
  { text: "No soy muy inteligente, pero sé lo que es el amor.", movie: "Forrest Gump", character: "Forrest Gump" },
  { text: "Mi mamá siempre decía que tienes que dejar atrás el pasado antes de seguir adelante.", movie: "Forrest Gump", character: "Forrest Gump" },
  { text: "Lo que hacemos en la vida tiene su eco en la eternidad.", movie: "Gladiador", character: "Máximo Décimo Meridio" },
  { text: "Mi nombre es Máximo Décimo Meridio, y alcanzaré mi venganza en esta vida o en la otra.", movie: "Gladiador", character: "Máximo Décimo Meridio" },
  { text: "¿No están entretenidos? ¿Acaso no es esto para lo que están aquí?", movie: "Gladiador", character: "Máximo Décimo Meridio" },
  { text: "O mueres como un héroe, o vives lo suficiente para verte convertido en el villano.", movie: "El Caballero de la Noche", character: "Harvey Dent" },
  { text: "Solo hace falta un pequeño empujón para que todo caiga en el caos.", movie: "El Caballero de la Noche", character: "Joker" },
  { text: "Si eres bueno en algo, jamás lo hagas gratis.", movie: "El Caballero de la Noche", character: "Joker" },
  { text: "¿Por qué tan serio?", movie: "El Caballero de la Noche", character: "Joker" },
  { text: "No es quién soy en el fondo, sino lo que hago lo que me define.", movie: "Batman Inicia", character: "Batman" },
  { text: "¿Por qué caemos, Bruce? Para aprender a levantarnos.", movie: "Batman Inicia", character: "Thomas Wayne" },
  { text: "Recuerda, Red: la esperanza es algo bueno, quizás lo mejor de todo, y las cosas buenas nunca mueren.", movie: "Sueños de Fuga", character: "Andy Dufresne" },
  { text: "Dedícate a vivir o dedícate a morir.", movie: "Sueños de Fuga", character: "Andy Dufresne" },
  { text: "Algunos pájaros no están hechos para estar enjaulados; sus plumas son demasiado brillantes.", movie: "Sueños de Fuga", character: "Red" },

  // 26 - 50
  { text: "¡Soy el rey del mundo!", movie: "Titanic", character: "Jack Dawson" },
  { text: "Si tú saltas, yo salto, ¿recuerdas?", movie: "Titanic", character: "Jack Dawson" },
  { text: "El corazón de una mujer es un océano profundo lleno de secretos.", movie: "Titanic", character: "Rose DeWitt Bukater" },
  { text: "Ganar el boleto para este barco fue lo mejor que me pasó en la vida, me trajo a ti.", movie: "Titanic", character: "Jack Dawson" },
  { text: "Si vas a construir una máquina del tiempo en un coche, ¿por qué no hacerlo con estilo?", movie: "Volver al Futuro", character: "Doc Brown" },
  { text: "¿Caminos? A donde vamos no necesitamos caminos.", movie: "Volver al Futuro", character: "Doc Brown" },
  { text: "Tu futuro no está escrito todavía, el de nadie lo está. Tu futuro es el que tú te hagas, así que haz uno bueno.", movie: "Volver al Futuro III", character: "Doc Brown" },
  { text: "He visto cosas que ustedes los humanos no creerían.", movie: "Blade Runner", character: "Roy Batty" },
  { text: "Todos esos momentos se perderán en el tiempo, como lágrimas en la lluvia. Es hora de morir.", movie: "Blade Runner", character: "Roy Batty" },
  { text: "Es toda una experiencia vivir con miedo, ¿verdad? Eso es lo que significa ser un esclavo.", movie: "Blade Runner", character: "Roy Batty" },
  { text: "La primera regla del Club de la Pelea es: no hablar del Club de la Pelea.", movie: "El Club de la Pelea", character: "Tyler Durden" },
  { text: "Las cosas que posees terminan poseyéndote a ti.", movie: "El Club de la Pelea", character: "Tyler Durden" },
  { text: "Únicamente después de haberlo perdido todo somos libres para hacer cualquier cosa.", movie: "El Club de la Pelea", character: "Tyler Durden" },
  { text: "¡Aquí está Johnny!", movie: "El Resplandor", character: "Jack Torrance" },
  { text: "Mucho trabajo y poca diversión hacen de Jack un tipo aburrido.", movie: "El Resplandor", character: "Jack Torrance" },
  { text: "¡Dile hola a mi pequeño amigo!", movie: "Scarface", character: "Tony Montana" },
  { text: "Yo siempre digo la verdad, incluso cuando miento.", movie: "Scarface", character: "Tony Montana" },
  { text: "El mundo es tuyo, chico.", movie: "Scarface", character: "Tony Montana" },
  { text: "La hamburguesa es la base de todo desayuno nutritivo.", movie: "Pulp Fiction", character: "Jules Winnfield" },
  { text: "El camino del hombre recto está por todos lados cercado por las iniquidades de los egoístas.", movie: "Pulp Fiction", character: "Jules Winnfield" },
  { text: "No hay nada más destructivo que una persona herida con el ego inflado.", movie: "Pulp Fiction", character: "Vincent Vega" },
  { text: "Toma la pastilla azul y la historia termina; toma la pastilla roja y te quedas en el País de las Maravillas.", movie: "Matrix", character: "Morfeo" },
  { text: "No pienses que lo eres, ¡sabe que lo eres!", movie: "Matrix", character: "Morfeo" },
  { text: "Tarde o temprano tendrás que entender, al igual que yo, que hay una gran diferencia entre conocer el camino y recorrer el camino.", movie: "Matrix", character: "Morfeo" },
  { text: "La matrix nos rodea, está en todas partes, incluso ahora mismo en esta misma habitación.", movie: "Matrix", character: "Morfeo" },

  // 51 - 75
  { text: "La vida siempre encuentra un camino.", movie: "Jurassic Park", character: "Dr. Ian Malcolm" },
  { text: "Estaban tan preocupados pensando si podían o no, que no se detuvieron a pensar si debían.", movie: "Jurassic Park", character: "Dr. Ian Malcolm" },
  { text: "¡Bienvenidos a Jurassic Park!", movie: "Jurassic Park", character: "John Hammond" },
  { text: "Un día nos despertamos y nos dimos cuenta de que estábamos haciendo historia.", movie: "El Lobo de Wall Street", character: "Jordan Belfort" },
  { text: "No hay nobleza en la pobreza. He sido un hombre rico y he sido un hombre pobre, y elijo ser rico cada maldita vez.", movie: "El Lobo de Wall Street", character: "Jordan Belfort" },
  { text: "Véndeme esta pluma.", movie: "El Lobo de Wall Street", character: "Jordan Belfort" },
  { text: "No es lo que te pasa, sino cómo reaccionas ante lo que te pasa. De eso se trata ganar.", movie: "Rocky Balboa", character: "Rocky Balboa" },
  { text: "El mundo no es un arcoíris ni nubes de algodón. Es un lugar frío y salvaje que te golpeará hasta ponerte de rodillas si se lo permites.", movie: "Rocky Balboa", character: "Rocky Balboa" },
  { text: "Nadie golpea tan fuerte como la vida, pero lo importante no es lo fuerte que golpeas, sino lo fuerte que pueden golpearte y seguir avanzando.", movie: "Rocky Balboa", character: "Rocky Balboa" },
  { text: "¡No hay dolor, no hay dolor!", movie: "Rocky III", character: "Rocky Balboa" },
  { text: "¡Adriana!", movie: "Rocky", character: "Rocky Balboa" },
  { text: "Buenos días, y por si no volvemos a vernos: ¡buenos días, buenas tardes y buenas noches!", movie: "El Show de Truman", character: "Truman Burbank" },
  { text: "Aceptamos la realidad del mundo con la que nos presentan. Es tan simple como eso.", movie: "El Show de Truman", character: "Christof" },
  { text: "Nunca olvides lo que eres, el resto del mundo no lo olvidará. Úsalo como armadura y nunca podrá ser usado para herirte.", movie: "Game of Thrones", character: "Tyrion Lannister" },
  { text: "El caos no es un pozo, el caos es una escalera.", movie: "Game of Thrones", character: "Meñique" },
  { text: "El amor es lo único que somos capaces de percibir que trasciende las dimensiones del tiempo y del espacio.", movie: "Interstellar", character: "Dra. Amelia Brand" },
  { text: "Solíamos mirar al cielo y preguntarnos por nuestro lugar en las estrellas; ahora miramos al suelo y nos preocupamos por nuestro lugar en el polvo.", movie: "Interstellar", character: "Cooper" },
  { text: "No entres dócilmente en esa buena noche. Ruge, enfurécete contra la muerte de la luz.", movie: "Interstellar", character: "Profesor Brand" },
  { text: "La gravedad puede cruzar las dimensiones, incluido el tiempo.", movie: "Interstellar", character: "Cooper" },
  { text: "El cine no es solo un sueño, es la vida proyectada en una sábana blanca.", movie: "Cinema Paradiso", character: "Alfredo" },
  { text: "Hagas lo que hagas, ámalo, como amabas la cabina del cine cuando eras un chiquillo.", movie: "Cinema Paradiso", character: "Alfredo" },
  { text: "La vida no es como la has visto en el cine; la vida es mucho más difícil.", movie: "Cinema Paradiso", character: "Alfredo" },
  { text: "Todos los hombres mueren, pero no todos los hombres realmente viven.", movie: "Braveheart: Corazón Valiente", character: "William Wallace" },
  { text: "Pueden quitarnos la vida, pero jamás nos quitarán ¡la libertad!", movie: "Braveheart: Corazón Valiente", character: "William Wallace" },
  { text: "Tu corazón es libre, ten el valor de seguirlo.", movie: "Braveheart: Corazón Valiente", character: "Malcolm Wallace" },

  // 76 - 100
  { text: "¡Espartanos! ¿Cuál es su oficio? ¡Ahu! ¡Ahu! ¡Ahu!", movie: "300", character: "Rey Leónidas" },
  { text: "¡Esta es mi tierra, esto es Esparta!", movie: "300", character: "Rey Leónidas" },
  { text: "Que tengan un buen desayuno, porque esta noche cenaremos en el infierno.", movie: "300", character: "Rey Leónidas" },
  { text: "Un gran poder conlleva una gran responsabilidad.", movie: "Spider-Man", character: "Tío Ben" },
  { text: "No importa cuántas veces caiga, siempre me vuelvo a levantar.", movie: "Spider-Man", character: "Peter Parker" },
  { text: "Y yo... yo soy... Iron Man.", movie: "Avengers: Endgame", character: "Tony Stark" },
  { text: "Yo soy inevitable.", movie: "Avengers: Endgame", character: "Thanos" },
  { text: "Te amo tres millones.", movie: "Avengers: Endgame", character: "Tony Stark" },
  { text: "Debiste apuntar a la cabeza.", movie: "Avengers: Infinity War", character: "Thanos" },
  { text: "Las decisiones más difíciles requieren las voluntades más fuertes.", movie: "Avengers: Infinity War", character: "Thanos" },
  { text: "La realidad a menudo es decepcionante.", movie: "Avengers: Infinity War", character: "Thanos" },
  { text: "No sé quién eres ni lo que quieres, pero te buscaré, te encontraré y te mataré.", movie: "Búsqueda Implacable", character: "Bryan Mills" },
  { text: "Tengo un conjunto de habilidades muy particular, adquiridas a lo largo de una carrera muy larga.", movie: "Búsqueda Implacable", character: "Bryan Mills" },
  { text: "En este mundo hay dos clases de personas, amigo: los que tienen la pistola cargada y los que cavan. Tú cavas.", movie: "El Bueno, el Malo y el Feo", character: "El Rubio" },
  { text: "Cuando tengas que disparar, dispara, no hables.", movie: "El Bueno, el Malo y el Feo", character: "Tuco" },
  { text: "Siempre nos quedará París.", movie: "Casablanca", character: "Rick Blaine" },
  { text: "De todos los bares de todas las ciudades de todo el mundo, ella tenía que entrar en el mío.", movie: "Casablanca", character: "Rick Blaine" },
  { text: "Creo que este es el comienzo de una hermosa amistad.", movie: "Casablanca", character: "Rick Blaine" },
  { text: "Tócala de nuevo, Sam. Tócala por los viejos tiempos.", movie: "Casablanca", character: "Ilsa Lund" },
  { text: "Carpe diem. Aprovechen el día, hagan que sus vidas sean extraordinarias.", movie: "La Sociedad de los Poetas Muertos", character: "John Keating" },
  { text: "¡Oh capitán, mi capitán!", movie: "La Sociedad de los Poetas Muertos", character: "Todd Anderson" },
  { text: "No leemos y escribimos poesía porque sea bonita; leemos y escribimos poesía porque pertenecemos a la raza humana.", movie: "La Sociedad de los Poetas Muertos", character: "John Keating" },
  { text: "Nunca dejes que nadie te diga que no puedes hacer algo, ni siquiera yo.", movie: "En Busca de la Felicidad", character: "Chris Gardner" },
  { text: "Si tienes un sueño, tienes que protegerlo. Las personas que no pueden hacer algo te dirán que tú tampoco puedes.", movie: "En Busca de la Felicidad", character: "Chris Gardner" },
  { text: "Esta pequeña parte de mi vida, este pequeño momento, se llama felicidad.", movie: "En Busca de la Felicidad", character: "Chris Gardner" },

  // 101 - 125
  { text: "Al infinito... ¡y más allá!", movie: "Toy Story", character: "Buzz Lightyear" },
  { text: "Hay una serpiente en mi bota.", movie: "Toy Story", character: "Woody" },
  { text: "Lo importante es que nos mantengamos juntos.", movie: "Toy Story 3", character: "Woody" },
  { text: "Adiós, vaquero.", movie: "Toy Story 3", character: "Andy Davis" },
  { text: "Hakuna Matata: significa no te preocupes por el resto de tus días.", movie: "El Rey León", character: "Timón y Pumba" },
  { text: "El pasado puede doler, pero tal como yo lo veo, puedes huir de él o aprender de él.", movie: "El Rey León", character: "Rafiki" },
  { text: "Recuerda quién eres. Eres mi hijo y el único y verdadero rey.", movie: "El Rey León", character: "Mufasa" },
  { text: "Mi tesoro... es mío, nuestro tesoro...", movie: "El Señor de los Anillos: Las Dos Torres", character: "Gollum" },
  { text: "¡No pasarás!", movie: "El Señor de los Anillos: La Comunidad del Anillo", character: "Gandalf" },
  { text: "Corran, insensatos.", movie: "El Señor de los Anillos: La Comunidad del Anillo", character: "Gandalf" },
  { text: "Incluso la persona más pequeña puede cambiar el curso del futuro.", movie: "El Señor de los Anillos: La Comunidad del Anillo", character: "Galadriel" },
  { text: "Solo tú puedes decidir qué hacer con el tiempo que se te ha concedido.", movie: "El Señor de los Anillos: La Comunidad del Anillo", character: "Gandalf" },
  { text: "Hay algo de bien en este mundo, señor Frodo, y vale la pena luchar por ello.", movie: "El Señor de los Anillos: Las Dos Torres", character: "Samwise Gamgee" },
  { text: "E.T., teléfono, mi casa.", movie: "E.T. El Extraterrestre", character: "E.T." },
  { text: "Estaré justo aquí.", movie: "E.T. El Extraterrestre", character: "E.T." },
  { text: "Me encanta el olor del napalm por la mañana. Huele a victoria.", movie: "Apocalypse Now", character: "Teniente Coronel Kilgore" },
  { text: "El horror... el horror...", movie: "Apocalypse Now", character: "Coronel Kurtz" },
  { text: "Houston, tenemos un problema.", movie: "Apolo 13", character: "Jim Lovell" },
  { text: "El fracaso no es una opción.", movie: "Apolo 13", character: "Gene Kranz" },
  { text: "¡No puedes soportar la verdad!", movie: "Cuestión de Honor", character: "Coronel Nathan R. Jessep" },
  { text: "Eres un mago, Harry.", movie: "Harry Potter y la Piedra Filosofal", character: "Rubeus Hagrid" },
  { text: "No son nuestras habilidades las que muestran cómo somos realmente, sino nuestras elecciones.", movie: "Harry Potter y la Cámara Secreta", character: "Albus Dumbledore" },
  { text: "Las palabras son, en mi no tan humilde opinión, nuestra más inagotable fuente de magia.", movie: "Harry Potter y las Reliquias de la Muerte", character: "Albus Dumbledore" },
  { text: "Después de tanto tiempo? —Siempre.", movie: "Harry Potter y las Reliquias de la Muerte", character: "Severus Snape" },
  { text: "¡Alégrame el día!", movie: "Harry el Sucio", character: "Harry Callahan" },

  // 126 - 150
  { text: "Debes hacerte una sola pregunta: '¿Me siento con suerte hoy?' Bueno, ¿te sientes con suerte?", movie: "Harry el Sucio", character: "Harry Callahan" },
  { text: "¡Muéstrame el dinero!", movie: "Jerry Maguire", character: "Rod Tidwell" },
  { text: "Tú me completas.", movie: "Jerry Maguire", character: "Jerry Maguire" },
  { text: "Me tuviste desde el 'hola'.", movie: "Jerry Maguire", character: "Dorothy Boyd" },
  { text: "La vida se mueve bastante rápido. Si no te detienes y miras a tu alrededor de vez en cuando, te la puedes perder.", movie: "Un Experto en Diversión", character: "Ferris Bueller" },
  { text: "No quiero necesitarte porque no puedo tenerte.", movie: "Los Puentes de Madison", character: "Robert Kincaid" },
  { text: "Un amor así no se repite dos veces en la vida.", movie: "Los Puentes de Madison", character: "Robert Kincaid" },
  { text: "El mejor truco que el diablo inventó fue convencer al mundo de que no existía.", movie: "Los Sospechosos de Siempre", character: "Keyser Söze" },
  { text: "Y así, como si nada... desapareció.", movie: "Los Sospechosos de Siempre", character: "Keyser Söze" },
  { text: "El ayer es historia, el mañana es un misterio, pero el hoy es un regalo. Por eso se llama presente.", movie: "Kung Fu Panda", character: "Maestro Oogway" },
  { text: "No hay ingredientes secretos; solo tienes que creer que es especial.", movie: "Kung Fu Panda", character: "Sr. Ping" },
  { text: "Nadaremos, nadaremos, en el mar, el mar, el mar...", movie: "Buscando a Nemo", character: "Dory" },
  { text: "Cuando la vida te desanime, ¿sabes qué debes hacer? Solo sigue nadando.", movie: "Buscando a Nemo", character: "Dory" },
  { text: "No cualquiera puede convertirse en un gran artista, pero un gran artista puede provenir de cualquier lugar.", movie: "Ratatouille", character: "Anton Ego" },
  { text: "No dejes que nadie defina tus límites por el lugar de donde vienes.", movie: "Ratatouille", character: "Gusteau" },
  { text: "La venganza nunca es un camino recto; es un laberinto en el que es muy fácil perderse.", movie: "Kill Bill: Volumen 1", character: "Hattori Hanzo" },
  { text: "Esa mujer merece su venganza... y nosotros merecemos morir.", movie: "Kill Bill: Volumen 2", character: "Budd" },
  { text: "Si buscas la paz, prepárate para la guerra.", movie: "John Wick 3: Parabellum", character: "Winston" },
  { text: "La gente no cambia con el tiempo, solo se vuelven más hábiles para esconder quiénes son.", movie: "House of Cards", character: "Frank Underwood" },
  { text: "Cada vez que suena una campana, un ángel se gana sus alas.", movie: "¡Qué Bello es Vivir!", character: "Zuzu Bailey" },
  { text: "Extraño lo que fuimos, pero agradezco lo que vivimos.", movie: "La La Land", character: "Sebastian Wilder" },
  { text: "Que nos volvamos a encontrar en otra vida donde el tiempo no juegue en nuestra contra.", movie: "La La Land", character: "Mia Dolan" },
  { text: "La cordura es una línea delgada que se rompe cuando miras demasiado tiempo al abismo.", movie: "La Isla Siniestra", character: "Teddy Daniels" },
  { text: "¿Qué sería peor: vivir como un monstruo o morir como un hombre bueno?", movie: "La Isla Siniestra", character: "Teddy Daniels" },
  { text: "El cine no es la copia de la realidad, es el misterio de los sueños hecho luz.", movie: "Mediateca Cinematográfica", character: "Videoteca" }
];
